import { useState } from "react";
import Grid from "./Grid";

// Game component:
// manages board state history
// handles move logic
// provides undo/reset/new game functionality
function Game() {
  // history stores all previous board states to support undo functionality
  const [history, setHistory] = useState([initLights(Array(25).fill(false))]);
  const count = history.length - 1;
  const lights = history[history.length - 1];

  // removes last move from history to restore previous board state
  function undo() {
    if (history.length === 1) {
      return;
    }
    const newhistory = history.slice();
    newhistory.pop();
    setHistory(newhistory);
  }

  function reset() {
    const newHistory = [history[0]];
    setHistory(newHistory);
  }

  function newGame() {
    const newHistory = [initLights(Array(25).fill(false))];
    setHistory(newHistory);
  }

  function handleClick(index) {
    if (checkWin(lights)) {
      return;
    }
    let newLights = toggleAdjacent(lights, index);
    setHistory((prev) => [...prev, newLights]);
  }

  // toggles the clicked light and its adjacent neighbors
  // checks left, right, top, bottom while preventing out-of-bounds access
  function toggleAdjacent(lights, index) {
    let newLights = lights.slice();
    newLights[index] = !newLights[index];
    const adjacentIndices = [];
    // check left neighbor (only if not in the leftmost column)
    if (index % 5 > 0) {
      adjacentIndices.push(index - 1);
    }
    // check right neighbor (only if not in the rightmost column)
    if (index % 5 < 4) {
      adjacentIndices.push(index + 1);
    }
    // check top neighbor (only if not in the top row)
    if (index > 4) {
      adjacentIndices.push(index - 5);
    }
    // check bottom neighbor (only if not in the bottom row)
    if (index < 20) {
      adjacentIndices.push(index + 5);
    }
    adjacentIndices.forEach((element) => {
      newLights[element] = !newLights[element];
    });
    return newLights;
  }

  // initializes the board with a random configuration of lights. 
  // It is solvable because it is generated by toggling from the all-off state.
  function initLights(lights) {
    let newLights = lights.slice();
    for (let i = 0; i < lights.length; i++) {
      if (Math.random() < 0.5) {
        newLights = toggleAdjacent(newLights, i);
      }
    }
    return newLights;
  }

  // player wins when all lights are turned off
  function checkWin(lights) {
    return lights.every((value) => value === false);
  }

  return (
    <>
      <div className="header">
        <h1>Lights Out</h1>
        <p>
          Click a light to toggle it and the adjacent lights. Turn off all the
          lights to win!
        </p>
      </div>

      <Grid lights={lights} handleClick={handleClick}></Grid>

      <p className="moves">
        {checkWin(lights) ? "You win!" : "Moves: " + count}
      </p>
      <div className="controls">
        <button className="btn" onClick={undo}>
          Move back
        </button>
        <button className="btn" onClick={newGame}>
          New Game
        </button>
        <button className="btn" onClick={reset}>
          Reset
        </button>
      </div>
    </>
  );
}

export default Game;
